### ISSUE TITLE
check-manifest as pre-commit-hook

### ISSUE THREAD

**Issue by tobiasraabe** [mgedmin/check-manifest#100]
Hi,

thanks for the package. MANIFEST.in was always a mystery for me, but your package makes it better.

Could you make your package available as a pre-commit hook? It is simple as adding a ``.pre-commit-hooks.yaml`` to your package. The content is detailed here: https://pre-commit.com/#new-hooks.

The advantage is that people can easily integrate your package in their workflow and check before each commit whether the MANIFEST.in is sufficiently specified.

Best

**Comment by mgedmin** [comment]
I thought it was up to the _users_ to add a `.pre-commit-hooks.yaml` to _their_ repositories if they want to run any tools such as `check-manifest` on every commit?  I don't see how adding one to my repository would help anyone.  (Unless as an example people could copy and paste?)

**Comment by tobiasraabe** [comment]
Users add a ``pre-commit-config.yaml`` to their repository to specify their pre-commits. It includes a hypothetical section like this:

```
-   repo: https://github.com/mgedmin/check-manifest
    rev: 0.39.dev0
    hooks:
    -   id: check-manifest
```

But, to use your repository as the source, your repo must include the ``.pre-commit-hooks.yaml``.

**Comment by mgedmin** [comment]
Ah!  That's neat!

I'd be happy to accept a pull request adding such a file.
