### ISSUE TITLE
0.38: test suite is failing

### ISSUE THREAD

**Issue by kloczek** [mgedmin/check-manifest#101]
<pre>+ /usr/bin/python3 setup.py test
running test
Searching for toml
Reading https://pypi.org/simple/toml/
Downloading https://files.pythonhosted.org/packages/a2/12/ced7105d2de62fa7c8fb5fce92cc4ce66b57c95fb875e9318dba7f8c5db0/toml-0.10.0-py2.py3-none-any.whl#sha256=235682dd292d5899d361a811df37e04a8828a5b1da3115886b73cf81ebc9100e
Best match: toml 0.10.0
Processing toml-0.10.0-py2.py3-none-any.whl
Installing toml-0.10.0-py2.py3-none-any.whl to /home/tkloczko/rpmbuild/BUILD/check-manifest-0.38/.eggs

Installed /home/tkloczko/rpmbuild/BUILD/check-manifest-0.38/.eggs/toml-0.10.0-py3.7.egg
Searching for mock
Reading https://pypi.org/simple/mock/
Downloading https://files.pythonhosted.org/packages/05/d2/f94e68be6b17f46d2c353564da56e6fb89ef09faeeff3313a046cb810ca9/mock-3.0.5-py2.py3-none-any.whl#sha256=d157e52d4e5b938c550f39eb2fd15610db062441a9c2747d3dbfa9298211d0f8
Best match: mock 3.0.5
Processing mock-3.0.5-py2.py3-none-any.whl
Installing mock-3.0.5-py2.py3-none-any.whl to /home/tkloczko/rpmbuild/BUILD/check-manifest-0.38/.eggs
writing requirements to /home/tkloczko/rpmbuild/BUILD/check-manifest-0.38/.eggs/mock-3.0.5-py3.7.egg/EGG-INFO/requires.txt

Installed /home/tkloczko/rpmbuild/BUILD/check-manifest-0.38/.eggs/mock-3.0.5-py3.7.egg
running egg_info
writing check_manifest.egg-info/PKG-INFO
writing dependency_links to check_manifest.egg-info/dependency_links.txt
writing entry points to check_manifest.egg-info/entry_points.txt
writing requirements to check_manifest.egg-info/requires.txt
writing top-level names to check_manifest.egg-info/top_level.txt
reading manifest file &apos;check_manifest.egg-info/SOURCES.txt&apos;
reading manifest template &apos;MANIFEST.in&apos;
writing manifest file &apos;check_manifest.egg-info/SOURCES.txt&apos;
running build_ext
test_get_vcs_files (tests.TestBzr) ... skipped &apos;bzr is not installed&apos;
test_get_vcs_files_added_but_uncommitted (tests.TestBzr) ... skipped &apos;bzr is not installed&apos;
test_get_vcs_files_deleted_but_not_removed (tests.TestBzr) ... skipped &apos;bzr is not installed&apos;
test_get_vcs_files_empty (tests.TestBzr) ... skipped &apos;bzr is not installed&apos;
test_get_vcs_files_in_a_subdir (tests.TestBzr) ... skipped &apos;bzr is not installed&apos;
test_get_vcs_files_nonascii_filenames (tests.TestBzr) ... skipped &apos;bzr is not installed&apos;
test_terminal_encoding_cp0 (tests.TestBzrTerminalCharsetDetectionOnNewPythons) ... skipped &quot;&apos;oem&apos; codec not available on Python before 3.6&quot;
test_terminal_encoding_cp0 (tests.TestBzrTerminalCharsetDetectionOnOldPythons) ... ok
test_terminal_encoding_not_known (tests.TestBzrTerminalCharsetDetectionOnOldPythons) ... ok
test_terminal_encoding_stdin_known (tests.TestBzrTerminalCharsetDetectionOnOldPythons) ... ok
test_terminal_encoding_stdout_known (tests.TestBzrTerminalCharsetDetectionOnOldPythons) ... ok
test_MANIFEST_in_does_not_need_to_be_added_to_be_considered (tests.TestCheckManifest) ... ok
test_all_is_well (tests.TestCheckManifest) ... ok
test_bad_ideas (tests.TestCheckManifest) ... ok
test_forgot_to_git_add_anything (tests.TestCheckManifest) ... ok
test_ignore_bad_ideas (tests.TestCheckManifest) ... ok
test_missing_source_files (tests.TestCheckManifest) ... ok
test_not_python_project (tests.TestCheckManifest) ... ok
test_python_from_path (tests.TestCheckManifest) ... ERROR
test_relative_pathname (tests.TestCheckManifest) ... ok
test_relative_python (tests.TestCheckManifest) ... ok
test_setup_py_does_not_need_to_be_added_to_be_considered (tests.TestCheckManifest) ... ok
test_suggestions (tests.TestCheckManifest) ... ok
test_suggestions_all_unknown_patterns (tests.TestCheckManifest) ... ok
test_suggestions_create (tests.TestCheckManifest) ... ok
test_suggestions_some_unknown_patterns (tests.TestCheckManifest) ... ok
test_suggestions_update (tests.TestCheckManifest) ... ok
test_read_config_no_config (tests.TestConfiguration) ... ok
test_read_manifest (tests.TestConfiguration) ... ok
test_read_manifest_no_manifest (tests.TestConfiguration) ... ok
test_read_pyproject_config_extra_ignores (tests.TestConfiguration) ... ok
test_read_pyproject_config_ignore_bad_ideas (tests.TestConfiguration) ... ok
test_read_pyproject_config_no_option (tests.TestConfiguration) ... ok
test_read_pyproject_config_no_section (tests.TestConfiguration) ... ok
test_read_pyproject_config_override_ignores (tests.TestConfiguration) ... ok
test_read_setup_config_extra_ignores (tests.TestConfiguration) ... ok
test_read_setup_config_ignore_bad_ideas (tests.TestConfiguration) ... ok
test_read_setup_config_no_option (tests.TestConfiguration) ... ok
test_read_setup_config_no_section (tests.TestConfiguration) ... ok
test_read_setup_config_override_ignores (tests.TestConfiguration) ... ok
test_detect_git_submodule (tests.TestGit) ... ok
test_get_vcs_files (tests.TestGit) ... ok
test_get_vcs_files_added_but_uncommitted (tests.TestGit) ... ok
test_get_vcs_files_deleted_but_not_removed (tests.TestGit) ... ok
test_get_vcs_files_empty (tests.TestGit) ... ok
test_get_vcs_files_in_a_subdir (tests.TestGit) ... ok
test_get_vcs_files_nonascii_filenames (tests.TestGit) ... ok
test_get_versioned_files_with_git_submodules (tests.TestGit) ... ok
test_get_vcs_files (tests.TestHg) ... skipped &apos;hg is not installed&apos;
test_get_vcs_files_added_but_uncommitted (tests.TestHg) ... skipped &apos;hg is not installed&apos;
test_get_vcs_files_deleted_but_not_removed (tests.TestHg) ... skipped &apos;hg is not installed&apos;
test_get_vcs_files_empty (tests.TestHg) ... skipped &apos;hg is not installed&apos;
test_get_vcs_files_in_a_subdir (tests.TestHg) ... skipped &apos;hg is not installed&apos;
test_get_vcs_files_nonascii_filenames (tests.TestHg) ... skipped &apos;hg is not installed&apos;
test (tests.TestMain) ... ok
test_exit_code_1_on_error (tests.TestMain) ... ok
test_exit_code_2_on_failure (tests.TestMain) ... ok
test_extra_ignore_args (tests.TestMain) ... ok
test_ignore_bad_ideas_args (tests.TestMain) ... ok
test_get_vcs_files (tests.TestSvn) ... ok
test_get_vcs_files_added_but_uncommitted (tests.TestSvn) ... ok
test_get_vcs_files_deleted_but_not_removed (tests.TestSvn) ... ok
test_get_vcs_files_empty (tests.TestSvn) ... ok
test_get_vcs_files_in_a_subdir (tests.TestSvn) ... ok
test_get_vcs_files_nonascii_filenames (tests.TestSvn) ... ok
test_svn_externals (tests.TestSvn) ... ok
test_svn_xml_parsing_warning (tests.TestSvnExtraErrors) ... ok
test_error (tests.TestUserInterface) ... ok
test_error_verbose (tests.TestUserInterface) ... ok
test_info (tests.TestUserInterface) ... ok
test_info_begin_continue_end (tests.TestUserInterface) ... ok
test_info_begin_continue_end_verbose (tests.TestUserInterface) ... ok
test_info_emits_newline_when_needed (tests.TestUserInterface) ... ok
test_info_emits_newline_when_needed_verbose (tests.TestUserInterface) ... ok
test_info_verbose (tests.TestUserInterface) ... ok
test_warning (tests.TestUserInterface) ... ok
test_warning_verbose (tests.TestUserInterface) ... ok
test_zest_releaser_check_all_okay (tests.TestZestIntegration) ... ok
test_zest_releaser_check_error_user_aborts (tests.TestZestIntegration) ... ok
test_zest_releaser_check_error_user_plods_on (tests.TestZestIntegration) ... ok
test_zest_releaser_check_failure_user_aborts (tests.TestZestIntegration) ... ok
test_zest_releaser_check_failure_user_plods_on (tests.TestZestIntegration) ... ok
test_zest_releaser_check_not_a_package (tests.TestZestIntegration) ... ok
test_zest_releaser_check_user_disagrees (tests.TestZestIntegration) ... ok
test_add_directories (tests.Tests) ... ok
test_copy_files (tests.Tests) ... ok
test_detect_vcs_no_vcs (tests.Tests) ... ok
test_extract_version_from_filename (tests.Tests) ... ok
test_file_matches (tests.Tests) ... ok
test_find_bad_ideas (tests.Tests) ... ok
test_find_suggestions (tests.Tests) ... ok
test_find_suggestions_generic_fallback_rules (tests.Tests) ... ok
test_find_suggestions_ignores_directories (tests.Tests) ... ok
test_format_list (tests.Tests) ... ok
test_format_missing (tests.Tests) ... ok
test_get_archive_file_list_tar (tests.Tests) ... ok
test_get_archive_file_list_tar_nonascii (tests.Tests) ... ok
test_get_archive_file_list_unrecognized_archive (tests.Tests) ... ok
test_get_archive_file_list_zip (tests.Tests) ... ok
test_get_archive_file_list_zip_nonascii (tests.Tests) ... ok
test_get_ignore_from_manifest (tests.Tests) ... ok
test_get_ignore_from_manifest_lines (tests.Tests) ... ok
test_get_ignore_from_manifest_warnings (tests.Tests) ... ok
test_get_one_file_in (tests.Tests) ... ok
test_get_one_file_in_empty_directory (tests.Tests) ... ok
test_get_one_file_in_too_many (tests.Tests) ... ok
test_glob_to_regexp (tests.Tests) ... ok
test_is_package (tests.Tests) ... ok
test_mkdtemp_readonly_files (tests.Tests) ... ok
test_normalize_names (tests.Tests) ... ok
test_rmtree_readonly_directories (tests.Tests) ... ok
test_rmtree_readonly_directories_and_files (tests.Tests) ... ok
test_rmtree_unreadable_directories (tests.Tests) ... ok
test_run_failure (tests.Tests) ... ok
test_run_no_such_program (tests.Tests) ... ok
test_run_success (tests.Tests) ... ok
test_strip_sdist_extras (tests.Tests) ... ok
test_strip_sdist_extras_with_manifest (tests.Tests) ... ok
test_strip_toplevel_name_empty_list (tests.Tests) ... ok
test_strip_toplevel_name_no_common_prefix (tests.Tests) ... ok
test_unicodify (tests.Tests) ... ok
add_prefix_to_each (check_manifest)
Doctest: check_manifest.add_prefix_to_each ... ok
strip_toplevel_name (check_manifest)
Doctest: check_manifest.strip_toplevel_name ... ok

======================================================================
ERROR: test_python_from_path (tests.TestCheckManifest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File &quot;/home/tkloczko/rpmbuild/BUILD/check-manifest-0.38/check_manifest.py&quot;, line 151, in run
    stderr=subprocess.STDOUT, cwd=cwd)
  File &quot;/usr/lib64/python3.7/subprocess.py&quot;, line 775, in __init__
    restore_signals, start_new_session)
  File &quot;/usr/lib64/python3.7/subprocess.py&quot;, line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: &apos;python&apos;: &apos;python&apos;

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &quot;/home/tkloczko/rpmbuild/BUILD/check-manifest-0.38/tests.py&quot;, line 1416, in test_python_from_path
    self.assertTrue(check_manifest(subdir, python=&apos;python&apos;))
  File &quot;/home/tkloczko/rpmbuild/BUILD/check-manifest-0.38/check_manifest.py&quot;, line 862, in check_manifest
    run([python, &apos;setup.py&apos;, &apos;sdist&apos;, &apos;-d&apos;, tempdir])
  File &quot;/home/tkloczko/rpmbuild/BUILD/check-manifest-0.38/check_manifest.py&quot;, line 153, in run
    raise Failure(&quot;could not run %s: %s&quot; % (command, e))
check_manifest.Failure: could not run [&apos;python&apos;, &apos;setup.py&apos;, &apos;sdist&apos;, &apos;-d&apos;, &apos;/tmp/check-manifest-js9fbtum-sdist&apos;]: [Errno 2] No such file or directory: &apos;python&apos;: &apos;python&apos;

----------------------------------------------------------------------
Ran 123 tests in 17.743s

FAILED (errors=1, skipped=13)
Test failed: &lt;unittest.runner.TextTestResult run=123 errors=1 failures=0&gt;
error: Test failed: &lt;unittest.runner.TextTestResult run=123 errors=1 failures=0&gt;
error: Bad exit status from /var/tmp/rpm-tmp.WcD7vx (%check)
</pre>

**Comment by mgedmin** [comment]
Let me know if the fix in git master works for you!
