### ISSUE TITLE
Support for Poetry

### ISSUE THREAD

**Issue by jtrakk** [mgedmin/check-manifest#103]
[PEP 517 and 518](https://medium.com/@grassfedcode/pep-517-and-518-in-plain-english-47208ca8b7a6) mean we don't need `setup.py` anymore and [Poetry](https://poetry.eustace.io) is an exciting new contender. Currently check-manifest [requires](https://github.com/mgedmin/check-manifest/blob/master/check_manifest.py#L832) `setup.py`. It would be great to have support for packaging tools that don't require `setup.py`.

**Comment by mgedmin** [comment]
Does Poetry make use of `MANIFEST.in`?  A quick skim of its documentation [implies that it doesn't](https://poetry.eustace.io/docs/pyproject/#include-and-exclude), which would make `check-manifest` not useful for projects using Poetry.

Am I mistaken?

**Comment by jtrakk** [comment]
Oh you're totally right, thanks for looking!
