### ISSUE TITLE
Does not work with setup.py-less packaging?

### ISSUE THREAD

**Issue by wimglenn** [mgedmin/check-manifest#105]
I use setuptools with declarative config (i.e. defined in [`setup.cfg`](https://setuptools.readthedocs.io/en/latest/setuptools.html#configuring-setup-using-setup-cfg-files)) and build system in `pyproject.toml`:

```
[build-system]
requires = [
    "setuptools >= 40.6.0",
    "wheel",
]
build-backend = "setuptools.build_meta"
```

This works fine to build wheels and sdist using the PEP 517 hooks ([here](https://github.com/pypa/setuptools/blob/v41.5.0/setuptools/build_meta.py#L252-L253)).

But check-manifest doesn't recognize this as valid Python project.

```
$ check-manifest
This is not a Python project (no setup.py).
```

**Comment by mgedmin** [comment]
Currently I run `python setup.py sdist -d $tmpdir` to create an sdist.  What command cam I run to create an sdist from a package that uses [PEP-517](https://www.python.org/dev/peps/pep-0517)?

**Comment by wimglenn** [comment]
any way you want to invoke the hook within isolated build environment. That could be “python -m pep517.build .”, for example.

It’s likely that we’ll get a “pip build” command if pypa will ever finish bikeshedding whether this should belong to pip, twine, or separate tool entirely..

**Comment by mgedmin** [comment]
[pep517](https://pypi.org/project/pep517/) seems workable, despite the "experimental" warning at the bottom.

**Comment by mgedmin** [comment]
One more request: can you link me to a public GitHub repository of a project that uses PEP-517 builds so I have something I can test with?

**Comment by wimglenn** [comment]
I've just pushed a minimal one for you to test with:
https://github.com/wimglenn/resources-example
https://pypi.org/project/resources-example/#files

Does that help?

**Comment by mgedmin** [comment]
Thank you, that was very helpful!

I've a working prototype in #106.

**Comment by wimglenn** [comment]
@mgedmin  Hi Marius, thanks for the prompt fix.  I've tried it out this morning, it works good for setuptools.  For other build systems such as flit and poetry the approach might not work. That's because check-manifest [copies source files to a temporary directory before build](https://github.com/mgedmin/check-manifest/blob/9ed067b2905c2bc6ad4c1f8acce1b543ea53d30e/check_manifest.py#L898), but those newer build systems use the VCS subdirs in order to auto-detect which files to include in sdist. There may be an exception during sdist build if the VCS dirs are missing.

It's a moot point because the whole point of using vcs here is to avoid reinventing manifest (i.e. if you use something other than distutils/setuptools then you don't have or want a `MANIFEST.in` file in the first place).  Feel free to just ignore/won't fix - the only possible use case I could see for `check-manifest` here would be for someone moving an existing project from `flit` back to `setuptools` or something like that.

**Comment by mgedmin** [comment]
Yeah, Poetry was already mentioned in https://github.com/mgedmin/check-manifest/issues/103.

MANIFEST.in seems like a very setuptools-specific thing, so perhaps it would make sense to check if pyproject.toml is using setuptools, and silently skip (without exiting with an error code) projects that use different build systems.

I think I'll wait for people to ask for that explicitly before I start doing any more work.

**Comment by wimglenn** [comment]
@mgedmin   Just a heads up, the link back to this issue from `CHANGES.rst` is broken (missing an "s" in "issues")

**Comment by mgedmin** [comment]
Thank you!  I'd created a vim snippet that generates these bad issue URLs, oops!
