### ISSUE TITLE
better ignore=

### ISSUE THREAD

**Issue by hivemall** [mgedmin/check-manifest#113]
assume exclude of top level folder setup_files

```
[check-manifest]
ignore =
    setup_files/*
    setup_files
```

If the  entire folder contents of setup_files is ignored, so should be the folder. Adding an empty folder to sdist&co makes no sense, thus rewrite so that the second line is redundant.

**Comment by mgedmin** [comment]
This looks like a duplicate of #98?

**Comment by hivemall** [comment]
it is, just crystal clear.

**Comment by mgedmin** [comment]
Do you have a reproducible example?  I find that having to set one up myself requires more energy than I can muster at the moment...

**Comment by mgedmin** [comment]
Heh, as usual whenever I complain in public, I find the energy I didn't have.

OTOH my current reproducer (from #98) is 150 megs and check-manifest takes 23 seconds to run.  I'd appreciate a smaller example, if you have one.

**Comment by mgedmin** [comment]
What the hell was I thinking when I made commit 559ef70?

(This was originally a Gist, therefore I had no commit messages back then!)
