### ISSUE TITLE
run() always decodes stderr even if decode is set to False

### ISSUE THREAD

**Issue by DudeNr33** [mgedmin/check-manifest#116]
The `run()` function decodes the `output` of the command only if `decode` is set to `True`.
`stderr` however is always decoded.
If the `status` is != 0, a `CommandFailed` exception is (tried to be) thrown. 
`output+stderr` is passed to the constructor which then leads to a TypeError ("can't concat str to bytes").

`Subversion.get_versioned_files()` calls the `run()` function with `decode=False` which will eventually lead to the TypeError if the svn command returns with a nonzero exit code.

**Comment by mgedmin** [comment]
Thank you for noticing and reporting this!
