### ISSUE TITLE
lists of files in version control and sdist do not match! 

### ISSUE THREAD

**Issue by MkLHX** [mgedmin/check-manifest#120]
Hi how to fix this issue ?

lists of files in version control and sdist do not match! 
missing from sdist:   .pypirc

**Comment by mgedmin** [comment]
This message means that you have a `.pypirc` file in your version control system, but when you do a `python setup.py sdist`, that file doesn't get included.

This is probably fine; it doesn't look like a file that every user of your package needs to have to be able to install and use your package.  So you can suppress the warning in one of two ways:

1. You can add a `ignore .pypirc` line to MANIFEST.in

2. You can add a `[check-manifest] ignore = .pypirc` section to your setup.cfg or tox.ini.

If, instead, you decided that you want your source distributions to contain this file for some reason, you could do that by adding an `include .pypirc` line to your MANIFEST.in.

(Apologies for late reply, I was on vacation and was ignoring computers)
