### ISSUE TITLE
confusion over error in egg_base option

### ISSUE THREAD

**Issue by altruios** [mgedmin/check-manifest#143]
I am confused as to why this is failing:
```
A:\repos\BinaryCounters> check-manifest --create    
```
produces this error
```
some files listed as being under source control are missing:
  BinaryCounters.py
['c:\\program files\\python36\\python.exe', 'setup.py', 'sdist', '-d', 'C:\\Users\\paulk\\AppData\\Local\\Temp\\check-manifest-u19axnq6-sdist'] failed (status 1):
running sdist
running egg_info
error: error in 'egg_base' option: 'src' does not exist or is not a directory
```
however it is:

```
#folder structure
BinaryCounters>
    build>
    dist>
    src>
        ...
        BinaryCounters.py
        BinaryCounters.egg-info>
    .gitignore
    setup.py
    tests.py
    ...
```
package_dir is marked as such in setup.py:
```
     package_dir={'': 'src'},
```

also:
```
check-manifest version 0.46
python version 3.6.4
windows 10
```

what exactly is this error?

**Comment by mgedmin** [comment]
The error is produced by running `python setup.py sdist`, not by check-manifest itself.

check-manifest runs `python setup.py sdist` twice:
- once in the source directory
- once in a clean copy of the source directory without any version control metadata

I'm assuming `python setup.py sdist` works fine in the source directory, or you would have noticed the problem before, so it's probably the second run that produces the error.  You can verify this by running check-manifest in verbose mode (`-v`).

If the src directory is missing in the clean copy, then check-manifest must've gotten confused while getting a list of versioned files.  What version control system do you use?

(I'm also a bit confused by the ordering of the messages, TBH.  I would expect the error message to show up first, because the printing differences is the very last thing that check-manifest does.  Maybe this can be explained by the messages getting printed to different output streams -- stdout versus stderr -- that then get aggregated together in some fixed order.)

**Comment by altruios** [comment]
yes, ```python setup.py sdist ``` works fine, but running check-manifests while open in the same directory produces this error above.

verbose produces this:
```
listing source files under version control: 4 files and directories
building an sdist: BinaryCounters-0.0.1.tar.gz: 4 files and directories
some files listed as being under source control are missing:
  BinaryCounters.py
copying source files to a temporary directory
building a clean sdist
['c:\\program files\\python36\\python.exe', 'setup.py', 'sdist', '-d', 'C:\\Users\\paulk\\AppData\\Local\\Temp\\check-manifest-dpmt5cql-sdist'] failed (status 1):
running sdist
running egg_info
error: error in 'egg_base' option: 'src' does not exist or is not a directory
```
which seems to confirm your suspicion: how would I test that, or fix that?

**Comment by mgedmin** [comment]
I was going to ask again: what version control system do you use?  But then I realized you mentioned a `.gitignore` in the original description, so now I'm going to assume Git.

```
listing source files under version control: 4 files and directories
building an sdist: BinaryCounters-0.0.1.tar.gz: 4 files and directories
some files listed as being under source control are missing:
  BinaryCounters.py
copying source files to a temporary directory
```

This is a hint!  The file that exists in your source tree is `src/BinaryCounters.py` (or `src\BinaryCounters.py`, using Windows native directory separators), but somehow the directory name gets lost.

To figure out why, I'll need to see the output of the command that check-manifest uses to produce a list of files in version control.  For git that would be `git ls-files`, if you don't use git submodules.

Also, it would be helpful to know what version of git you have.

**Comment by altruios** [comment]
using git version 2.29.2.windows.2
```
PS A:\repos\BinaryCounters> git ls-files
.gitattributes   
BinaryCounters.py
LICENSE
README.md        
tests.py
```

verbose isn't any extra help:
```
PS A:\repos\BinaryCounters> git ls-files -v
H .gitattributes   
H BinaryCounters.py
H LICENSE
H README.md        
H tests.py
```

it does not show any of the folders (lib,dist,src) ?

**Comment by mgedmin** [comment]
That's what's super-weird to me!

Did you recently move the files into subdirectories?  What does `git status` report?  Is the repository public so I could boot into Windows and try it myself?

**Comment by altruios** [comment]
recently changed the structure to the folder structure above.
I've just pushed the src folder to the repo - that is public:
https://github.com/altruios/BinaryCounters

When I get home I'll check what git status reports.

**Comment by altruios** [comment]
I have some how fixed it: and I wish I could reproduce what exactly I did... but it was some combination of 

deleting the dis/build dir, rebuilding them with ``` python setup.py sdist ``` and ``` python setup.py bdist_wheel ``` (neither of which were giving any warnings or errors)  and calling ``` check-manifest --create ``` in some order that worked (and now every variation  I try seems to work): so it seems to have resolved itself.

**Comment by mgedmin** [comment]
The symptoms would all be explained if what happened was you'd moved BinaryCounters.py into the src subdirectory manually (i.e. not using `git mv`), but didn't run `git add` to tell git about the move before running `check-manifest`.
