### ISSUE TITLE
do not depend on obsolete mock

### ISSUE THREAD

**Issue by pgajdos** [mgedmin/check-manifest#151]
Please consider to use unittest.mock instead.

**Comment by mgedmin** [comment]
I don't mind. I have no more reason not to use unittest.mock, given that Python 2.7 is no longer supported.

OTOH I don't feel any particular urgency for migrating away from it.  I will accept a PR replacing mock with unittest.mock, but I myself have no plans of doing that until actual problems show up (like tests failing on a new Python version or something like that).
