### ISSUE TITLE
git submodules don’t work

### ISSUE THREAD

**Issue by hynek** [mgedmin/check-manifest#61]
Currently if I have a git submodule, check-manifest complains about it missing in sdist and VCS at once: https://travis-ci.org/hynek/argon2_cffi/jobs/95785495

**Comment by mgedmin** [comment]
This is because check-manifest uses `git ls-files` to discover what's under version control, and apparently `git ls-files` doesn't recurse into submodules.

Steps to reproduce:

- `git clone --recursive https://github.com/hynek/argon2_cffi` (I tested with commit c8d9535)
- `check-manifest argon2_cffi`

**Comment by mgedmin** [comment]
Plan:
- run `git ls-files` as usual
- figure out what the submodules are by running `git submodule --quiet foreach --recursive 'echo $path'`
- for each submodule run `git ls-files` in that subdirectory
- append the correct submodule path prefix to all the files retunred in each `git ls-files` invocation
- concatenate all the lists
- profit!

**Comment by mgedmin** [comment]
With current git master I get the following output if I try with argon2_cffi:
```
lists of files in version control and sdist do not match!
missing from VCS:
  libargon2/.git
```

Do you really want your source tarballs to contain a `.git` file with `gitdir: ../.git/modules/libargon2` as the content?  If not, you may want to add

```
exclude src/argon2/_ffi.py .git
```

to your MANIFEST.in.

**Comment by hynek** [comment]
I can confirm that the current master works if I exclude the .git.

Release? :dog:

**Comment by mgedmin** [comment]
I will release 0.30 when my Jenkins confirms that the code works on Windows.

This is taking longer than I expected for reasons I don't understand.  [Previously builds](https://jenkins.gedmin.as/job/check-manifest-on-windows/buildTimeTrend) would finish in 10 minutes.  [This build](https://jenkins.gedmin.as/job/check-manifest-on-windows/408/console) is taking 53 minutes and counting (and it has test failures I already fixed, which will be tested in a new build).

I rdesktop'ed manually to my Jenkins machine and ran the tests using `nose`, while Jenkins was still busy on the same machine, and my manual test run took 35 seconds for one Python version.  I don't understand what is happening, and I lack my usual tools (pstree, strace) on the unfamiliar Windows platform to debug it.

In the meantime I'm exploring Appveyor.

**Comment by mgedmin** [comment]
Somehow the new code produces a duplicate directory name on Windows:
https://ci.appveyor.com/project/mgedmin/check-manifest/build/1.0.4/job/ag3ku5s5qsmq22gq

**Comment by mgedmin** [comment]
Also, any idea why `pip install bzr` doesn't place a bzr executable on my %PATH%?

**Comment by mgedmin** [comment]
Down to [one error on Appveyor](https://ci.appveyor.com/project/mgedmin/check-manifest/build/build-7.master/job/gttb6p0kg9q64510), which is the same error I get when I run the tests manually on the Jenkins machine -- but not when Jenkins runs the tests for me.

**Comment by mgedmin** [comment]
At this point I have tests passing when I run `.tox/py27/scripts/nosetests`, and failing when I run `tox -e py27`.  But there are no locale environment variables on Windows!  ... are there?

Also, I seriously question my life choices.

**Comment by hynek** [comment]
welcome to my life. :)

if it makes you feel any better, I fought (and lost) Windows too today

**Comment by mgedmin** [comment]
Yay: I got the tests to pass on Appveyor and manually.

Boo: the tests now fail on Jenkins.

Do I even care?

**Comment by mgedmin** [comment]
check-release 0.30 is out on PyPI.

**Comment by lorengordon** [comment]
@mgedmin, I'm still seeing duplicate directory names on Windows, using check-manifest 0.32 (and building from source). I added this to get past it temporarily, but obviously not fixing the root cause. Any ideas?

```diff
# git diff
diff --git a/check_manifest.py b/check_manifest.py
index 948cd7c..ec761f9 100755
--- a/check_manifest.py
+++ b/check_manifest.py
@@ -186,6 +186,7 @@ def copy_files(filelist, destdir):

     File names should be relative to the current working directory.
     """
+    print('filelist is "{0}"'.format(filelist))
     for filename in filelist:
         destfile = os.path.join(destdir, filename)
         # filename should not be absolute, but let's double-check
@@ -194,7 +195,10 @@ def copy_files(filelist, destdir):
         if not os.path.isdir(destfiledir):
             os.makedirs(destfiledir)
         if os.path.isdir(filename):
-            os.mkdir(destfile)
+            try:
+                os.mkdir(destfile)
+            except WindowsError:
+                pass
         else:
             shutil.copy2(filename, destfile)
```

**Comment by lorengordon** [comment]
This diff starts to expose the underlying problem. The same directory is sometimes returned twice by `vcs.get_versioned_files()`, once with forward slashes and once with backslashes.

```diff
diff --git a/check_manifest.py b/check_manifest.py
index 948cd7c..90dd9b5 100755
--- a/check_manifest.py
+++ b/check_manifest.py
@@ -30,6 +30,7 @@ import zipfile
 from contextlib import contextmanager, closing
 from distutils.text_file import TextFile
 from xml.etree import cElementTree as ET
+from pprint import pprint

 try:
     import ConfigParser
@@ -194,7 +195,10 @@ def copy_files(filelist, destdir):
         if not os.path.isdir(destfiledir):
             os.makedirs(destfiledir)
         if os.path.isdir(filename):
-            os.mkdir(destfile)
+            try:
+                os.mkdir(destfile)
+            except WindowsError:
+                pass
         else:
             shutil.copy2(filename, destfile)

@@ -433,6 +437,10 @@ def detect_vcs():
 def get_vcs_files():
     """List all files under version control in the current directory."""
     vcs = detect_vcs()
+    print("\n\nPrinting sorted get_versioned_files\n\n")
+    pprint(sorted(vcs.get_versioned_files()))
+    print("\n\nPrinting sorted normalize_names\n\n")
+    pprint(sorted(normalize_names(vcs.get_versioned_files())))
     return normalize_names(vcs.get_versioned_files())
```

**Comment by lorengordon** [comment]
Ok, think I got it. `_git_ls_files()` returns file paths with forward slashes. For files in submodules, `add_prefix_to_each()` is called, which uses `os.path.join()` and ends up replacing the forward slashes with backslashes. Since not every file is in a submodule, the list of files ends up with some files that use forward slashes and others that use backslashes. This is probably only a problem for us because we're packaging submodules in a static directory within our src/project directory, so both our src and the submodules share a bit of the path. E.g.

`<project_root>/src/project/__init__.py`
`<project_root>/src/project/<modules>/`
`<project_root>/src/project/static/<submodules>`

If it were more like this, there wouldn't be any path overlap and we wouldn't have seen the issue:

`<project_root>/src/project/__init__.py`
`<project_root>/src/project/<modules>/`
`<project_root>/static/<submodules>`

**Comment by mgedmin** [comment]
@lorengordon Thank you for the investigation!  (Also, next time can you please open a new issue instead of commenting on an old closed one?)
