### ISSUE TITLE
Config to ignore bad_ideas

### ISSUE THREAD

**Issue by gregory-marton** [mgedmin/check-manifest#67]
I have a case where a submodule not under my control has a bad_idea (an autogenerated file in VCS). I would like to be able to use check-manifest as part of an acceptance test suite, but there seems to be no way to tell it to just grumble silently and ignore this one file. Would you welcome a patch that created an option similar to ignore for this, perhaps named `ignore_bad_ideas`? Is there some easy workaround?

**Comment by mgedmin** [comment]
That sounds like a good idea.

It'll also help with #38.

**Comment by brechtm** [comment]
Is there any progress with respect to this issue? Thanks.
