### ISSUE TITLE
Handling of read-only files

### ISSUE THREAD

**Issue by adrianschlatter** [mgedmin/check-manifest#74]
check-manifest fails with PermissionErrror if it encounters read-only files (see screen-shot below). This is a common situation in svn working-copies with locked files (svn:needs-lock property applied).

I expect that read-only files do not affect the operation of check-manifest (unless the file is missing from the dist, of course).

![permissionerror](https://cloud.githubusercontent.com/assets/10478149/18464323/a3bef5a6-7990-11e6-9c43-7b8d87c62806.jpg)

**Comment by mgedmin** [comment]
I was unable to reproduce this on Linux.

Judging from the traceback, the error happens when check-manifest is trying to remove its temporary directory.

The fix is probably to do what 7ad8114539181e2bf49a7d2644e7f38949332661 did in tests, only in the main code.

**Comment by mgedmin** [comment]
@adrianschlatter: can you test the fix in #75?

**Comment by adrianschlatter** [comment]
Confirmed to work properly (i.e., no errors with read-only files) with python2.7 and python3.5. Thanks!

Any idea when that fix will be available on pypi?

**Comment by mgedmin** [comment]
I plan to push the fix today.

(It occured to me that maybe I want to add a regression test for this.)

**Comment by mgedmin** [comment]
check-manifest 0.35 is out.

**Comment by adrianschlatter** [comment]
It has been a pleasure to work with you ;) Thanks.
