### ISSUE TITLE
FileExistsError on Every Run

### ISSUE THREAD

**Issue by fny** [mgedmin/check-manifest#84]
For some strange reason, I'm getting a FileExistsError on every run:

```
Traceback (most recent call last):
  File "/Users/faraz/.pyenv/versions/3.6.2/envs/smuggler-3.6/bin/check-manifest", line 11, in <module>
    sys.exit(main())
  File "/Users/faraz/.pyenv/versions/3.6.2/envs/smuggler-3.6/lib/python3.6/site-packages/check_manifest.py", line 920, in main
    update=args.update, python=args.python):
  File "/Users/faraz/.pyenv/versions/3.6.2/envs/smuggler-3.6/lib/python3.6/site-packages/check_manifest.py", line 808, in check_manifest
    copy_files(existing_source_files, tempsourcedir)
  File "/Users/faraz/.pyenv/versions/3.6.2/envs/smuggler-3.6/lib/python3.6/site-packages/check_manifest.py", line 217, in copy_files
    os.mkdir(destfile)
FileExistsError: [Errno 17] File exists: '/var/folders/lg/m3q3m8z11458bpm2mbnl235h0000gn/T/check-manifest-eeltcupj-sources/.'
```

System Version: macOS 10.12.5 (16F73)
Kernel Version: Darwin 16.6.0

**Comment by mgedmin** [comment]
Oh, interesting!  Somehow you end up with a `.` in the `existing_source_files` list.  A quick fix would be to add `.` to the default `IGNORE` list, but I'd like to understand where it comes from (in case I end up with a `.` entry in a subdirectory or something).

What version control system do you use for the project you're feeding to check-manifest?

Is there any way for me to try and reproduce this with your source repo (e.g. is it open-source code)?

**Comment by fny** [comment]
Here's the repo: https://github.com/fny/smuggler

**Comment by mgedmin** [comment]
I cannot reproduce the error on Linux, using check-manifest 0.35 and git 2.11.0.

Your repository doesn't use submodules, so what check-manifest does is run `git ls-files`.  When I try that on your repo, I get

```
.gitignore
.travis.yml
LICENSE.txt
MANIFEST.in
README.rst
fixtures/contraband.py
setup.cfg
setup.py
smuggler.py
tests/__init__.py
tests/fixtures/fake_drugs.py
tests/fixtures/inner_russian_doll.py
tests/fixtures/outer_russian_doll.py
tests/test_smuggle.py
tox.ini
```

Do you get anything different if you do `git ls-files`?  E.g. if your git prints every filename as `./tox.ini` etc, that could probably explain this bug.

Also, can you tell me what `git --version` prints for you?

**Comment by SpotlightKid** [comment]
This can also happen, if you are working in a git repo, which you have just initialized with `git init`, but haven't commited anything yet.

**Comment by mgedmin** [comment]
I can reproduce this after a fresh `git init`!

The core cause is that `''.split('\0')` returns `['']` rather than `[]` in Python, which then gets normalized to `['.']`.
